### ISSUE TITLE
Bug in check_partials for distributed component

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#2155] opened 2021-06-23 19:11 UTC
### Summary of Issue

Some kind of weird variable sizing problem, related to components with matrix free partials and check_partials. 
### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

When running the provided test case with `mpiexec -n 2 python test.py` the following error occurs: 

```Traceback (most recent call last):
  File "tmp.py", line 123, in <module>
    partials = prob.check_partials(compact_print=True, method='cs')
  File "/Users/jsgray/work/packages/openmdao/openmdao/core/problem.py", line 1221, in check_partials
    comp._apply_linear(None, _contains_all, mode)
  File "/Users/jsgray/work/packages/openmdao/openmdao/core/explicitcomponent.py", line 363, in _apply_linear
    self._compute_jacvec_product_wrapper(*args)
  File "/Users/jsgray/work/packages/openmdao/openmdao/core/explicitcomponent.py", line 294, in _compute_jacvec_product_wrapper
    self.compute_jacvec_product(*args)
  File "tmp.py", line 84, in compute_jacvec_product
    d_inputs[f'{output.name}_serial'] = self.comm.bcast(
  File "/Users/jsgray/work/packages/openmdao/openmdao/vectors/vector.py", line 371, in __setitem__
    self.set_var(name, value)
  File "/Users/jsgray/work/packages/openmdao/openmdao/vectors/vector.py", line 558, in set_var
    raise ValueError(f"{self._system().msginfo}: Failed to set value of "
ValueError: 'converter' <class DistributedConverter>: Failed to set value of 'out1_serial': could not broadcast input array from shape (4,4) into shape (5).
```

### Example

```
import numpy as np
import openmdao.api as om
from openmdao.utils.mpi import MPI


class DistributedVariableDescription:
    """
    Attributes of a variable for conversion from serial to distributed
    or distributed to serial
    """

    def __init__(self, name: str, shape: tuple, tags=[]):
        self.name = name
        self.shape = shape
        self.tags = tags


class DistributedConverter(om.ExplicitComponent):
    """
    An ExplicitComponent to convert from distributed to serial and serial to distributed variables.
    Mphys requires the coupling inputs and outputs to be distributed variables, so this
    class is provided to help with those conversions.
    For each mphys variable, a {variable}_serial version is created for the nonparallel solver to connect to and the
    distributed version will have the full vector on the root processor and zero length on the other processors.
    Given a list of distributed inputs in the options, the component will add variables to the inputs as distributed and
    produce {variable}_serial as outputs.
    Given a list of distributed outputs in the options, the component will add variables to the outputs as distributed and
    add {variable}_serial as inputs.

    """

    def initialize(self):
        self.options.declare(
            'distributed_inputs', default=[],
            desc='List of DistributedVariableDescription objects that will be converted from distributed to serial')
        self.options.declare(
            'distributed_outputs', default=[],
            desc='List of DistributedVariableDescription objects that will be converted from serial to distributed')

    def setup(self):
        for input in self.options['distributed_inputs']:
            self.add_input(input.name, shape_by_conn=True, tags=input.tags, distributed=True)
            self.add_output(f'{input.name}_serial', shape=input.shape, distributed=False)

        for output in self.options['distributed_outputs']:
            shape = output.shape if self.comm.Get_rank() == 0 else 0
            self.add_input(f'{output.name}_serial', shape_by_conn=True, distributed=False)
            self.add_output(output.name, shape=shape, tags=output.tags, distributed=True)

    def compute(self, inputs, outputs):
        for input in self.options['distributed_inputs']:
            if self.comm.Get_rank() == 0:
                outputs[f'{input.name}_serial'] = inputs[input.name]
            outputs[f'{input.name}_serial'] = self.comm.bcast(outputs[f'{input.name}_serial'])

        for output in self.options['distributed_outputs']:
            if self.comm.Get_rank() == 0:
                outputs[output.name] = inputs[f'{output.name}_serial']

    def compute_jacvec_product(self, inputs, d_inputs, d_outputs, mode):
        if mode == 'fwd':
            for input in self.options['distributed_inputs']:
                if input.name in d_inputs and f'{input.name}_serial' in d_outputs:
                    if self.comm.Get_rank() == 0:
                        d_outputs[f'{input.name}_serial'] += d_inputs[input.name]
                    d_outputs[f'{input.name}_serial'] = self.comm.bcast(
                        d_outputs[f'{input.name}_serial'])

            for output in self.options['distributed_outputs']:
                if output.name in d_outputs and f'{output.name}_serial' in d_inputs:
                    if self.comm.Get_rank() == 0:
                        d_outputs[output.name] += d_inputs[f'{output.name}_serial']

        if mode == 'rev':
            for input in self.options['distributed_inputs']:
                if input.name in d_inputs and f'{input.name}_serial' in d_outputs:
                    if self.comm.Get_rank() == 0:
                        d_inputs[input.name] += d_outputs[f'{input.name}_serial']

            for output in self.options['distributed_outputs']:
                if output.name in d_outputs and f'{output.name}_serial' in d_inputs:
                    if self.comm.Get_rank() == 0:
                        d_inputs[f'{output.name}_serial'] += d_outputs[output.name]
                    d_inputs[f'{output.name}_serial'] = self.comm.bcast(
                        d_inputs[f'{output.name}_serial'])


prob = om.Problem()

vars_in = [
    DistributedVariableDescription('in1', shape=(4, 4), tags=['mphys_coupling']),
    DistributedVariableDescription('in2', shape=(10), tags=['mphys_coordinates'])
]

vars_out = [
    DistributedVariableDescription('out1', shape=(5), tags=['mphys_coupling']),
    DistributedVariableDescription('out2', shape=(15), tags=['mphys_result'])
]

inputs = prob.model.add_subsystem('inputs', om.IndepVarComp())

in1_shape = (4, 4) if MPI.COMM_WORLD.Get_rank() == 0 else 0
in2_shape = 10 if MPI.COMM_WORLD.Get_rank() == 0 else 0
inputs.add_output('in1', val=np.ones(in1_shape, dtype=float), distributed=True)
inputs.add_output('in2', val=np.arange(in2_shape, dtype=float), distributed=True)

out1_shape = 5
out2_shape = 15
inputs.add_output('out1', val=np.ones(out1_shape, dtype=float), distributed=False)
inputs.add_output('out2', val=np.arange(out2_shape, dtype=float), distributed=False)

prob.model.add_subsystem('converter', DistributedConverter(
    distributed_inputs=vars_in, distributed_outputs=vars_out))

for var in ['in1', 'in2']:
    prob.model.connect(f'inputs.{var}', f'converter.{var}')
for var in ['out1', 'out2']:
    prob.model.connect(f'inputs.{var}', f'converter.{var}_serial')

prob.setup(force_alloc_complex=True)


partials = prob.check_partials(compact_print=True, method='cs')
```

**Comment by tadkollar** [comment] 2021-07-29 16:11
I found that the example hung with master due to a change in `System._setup_global_shapes()` that I PRed earlier in the week. I pushed a fix for that to my `cp2155` branch. However, I can't reproduce the check_partials error with either that branch or the current release. I attached the output I get with `mpirun -n 2 python cp_test.py`.

[output.txt](https://github.com/OpenMDAO/OpenMDAO/files/6901968/output.txt)

**Comment by Kenneth-T-Moore** [comment] 2021-08-12 20:28
The exception no longer occurs, but the reverse-mode derivatives are not correct in MPI. However, this is a problem in the component's `compute_jacvec_product`, where the matrix vector product in reverse mode needs to be reduced (sum) via the MPI operation.  The derivatives are correct with the following modifications to the component:

```
        if mode == 'rev':
            for input in self.options['distributed_inputs']:
                serial_name = f'{input.name}_serial'
                if input.name in d_inputs and serial_name in d_outputs:
                    if MPI:
                        mvp = np.zeros(d_outputs[serial_name].shape)
                        self.comm.Allreduce(d_outputs[serial_name], mvp, op=MPI.SUM)
                    else:
                        mvp = d_outputs[serial_name]
                    if self.comm.rank == 0:
                        d_inputs[input.name] += mvp

            for output in self.options['distributed_outputs']:
                if output.name in d_outputs and f'{output.name}_serial' in d_inputs:
                    if self.comm.Get_rank() == 0:
                        d_inputs[f'{output.name}_serial'] += d_outputs[output.name]
                    d_inputs[f'{output.name}_serial'] = self.comm.bcast(
                        d_inputs[f'{output.name}_serial'])
```

**Closed by Kenneth-T-Moore** 2021-08-12 20:28 UTC
Labels: bug
