### ISSUE TITLE
Be consistent in code examples when 

### ISSUE THREAD

**Issue by hschilling** [OpenMDAO/OpenMDAO#1390] opened 2020-05-04 19:56 UTC
### Summary of Issue

In the docs, there is inconsistency in how we setup models in terms of whether we explicitly create a Group at the top level.

### Issue Type

- [ ] Bug
- [x] Enhancement  

### Description

Choose a recommended way to do this and implement that across all examples used in the docs. 

Best to wait until the AutoIVC implementation is in place. 

### Example

http://openmdao.org/twodocs/versions/latest/getting_started/index.html - no Group
http://openmdao.org/twodocs/versions/latest/basic_guide/first_analysis.html - we make a Group

### Environment

All

**Comment by JustinSGray** [comment] 2020-08-18 13:16
The recommended way is to not create a new top level group. Just use the one that is there.

**Comment by swryan** [comment] 2020-08-18 13:42
Another perhaps important viewpoint is that a model can exist independently from a problem, as exemplified by the second example.

The problem can be defined based on a pre-existing model (also useful if the model is a class that sub-classes Group).  

There is not a "top level group that is there" until the Problem is instantiated, and if the model is passed in the constructor then the externally constructed model is that Group.

I'm not convinced it's required to only ever show one possible way to do things.

**Comment by robfalck** [comment] 2021-08-11 18:27
Closing for now, I agree with @swryan here.

**Closed by robfalck** 2021-08-11 18:27 UTC
Labels: docs

**Comment by hschilling** [comment] 2021-08-11 18:35
Could the docs talk about what @swryan mentioned ? 

This issue was created because it created confusion for users and they didn't know what was the correct way to do things. I realize that the answer is that it depends but we should say that.
