### ISSUE TITLE
COBYLA with scaling

### ISSUE THREAD

**Issue by mifm** [OpenMDAO/OpenMDAO#942] opened 2019-05-27 09:13 UTC
Using COBYLA with the ref argument set or scaling in the objective causes optimization to fail:
```
from openmdao.api import Problem, ScipyOptimizeDriver, ExecComp, IndepVarComp

# We'll use the component that was defined in the last tutorial
from openmdao.test_suite.components.paraboloid import Paraboloid

def get_prob():
    # build the model
    prob = Problem()
    indeps = prob.model.add_subsystem('indeps', IndepVarComp())
    indeps.add_output('x', 3.0)
    indeps.add_output('y', -4.0)
    
    prob.model.add_subsystem('parab', Paraboloid())
    
    # define the component whose output will be constrained
    prob.model.add_subsystem('const', ExecComp('g = x + y'))
    
    prob.model.connect('indeps.x', ['parab.x', 'const.x'])
    prob.model.connect('indeps.y', ['parab.y', 'const.y'])
    
    # setup the optimization
    prob.driver = ScipyOptimizeDriver()
    prob.driver.options['optimizer'] = 'COBYLA'
    
    # to add the constraint to the model
    prob.model.add_constraint('const.g', lower=0, upper=10.)
    return prob

# Using ref0 and ref:
prob = get_prob()
prob.model.add_design_var('indeps.x', **{'ref0': 0, 'ref': 2, 'lower': -50, 'upper': 50})
prob.model.add_design_var('indeps.y', **{'ref0': 0, 'ref': 2, 'lower': -50, 'upper': 50})
prob.model.add_objective('parab.f_xy', scaler = 1)
prob.setup()
prob.run_driver()

# minimum value
print(prob['parab.f_xy'])

# location of the minimum
print(prob['indeps.x'])
print(prob['indeps.y'])

# Using scaler on the objective:
prob = get_prob()
prob.model.add_design_var('indeps.x', **{'ref0': 0, 'ref': 1, 'lower': -50, 'upper': 50})
prob.model.add_design_var('indeps.y', **{'ref0': 0, 'ref': 1, 'lower': -50, 'upper': 50})
prob.model.add_objective('parab.f_xy', scaler = 2)
prob.setup()
prob.run_driver()

# minimum value
print(prob['parab.f_xy'])

# location of the minimum
print(prob['indeps.x'])
print(prob['indeps.y'])

```
With SLSQP this runs fine.

**Comment by Kenneth-T-Moore** [comment] 2020-01-17 21:57
I have to apologize for this being open for so long; somehow it slipped though the cracks.  Anyway, I think the problem is fixed now, and this issue will get closed automatically when the fix is merged into master.

**Closed** 2020-01-18 04:17 UTC
