### ISSUE TITLE
Issue: Failures in test

### ISSUE THREAD

**Issue by RuruX** [OpenMDAO/OpenMDAO#849] opened 2019-02-13 06:55 UTC
Following the instruction, I found two failures when testing OpenMDAO. And the installation statements are attached.
[OpenMDAO_install.txt](https://github.com/OpenMDAO/OpenMDAO/files/2859163/OpenMDAO_install.txt)

...............................................................................................................

The following tests failed:
test_linear_block_gs.py:TestBGSSolver.test_implicit_cycle_precon
test_scipy_iter_solver.py:TestScipyKrylovFeature.test_specify_precon

Passed:  1536
Failed:  2
Skipped: 238

Ran 1776 tests using 1 processes
Wall clock time:   00:02:56.59

xiangrudeMacBook-Air:~ xiangru$ python
Python 3.7.1 (default, Dec 14 2018, 13:28:58) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform, sys
>>> info = platform.uname()
>>> (info.system, info.version), (info.machine, info.processor), sys.version
**(('Darwin', 'Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64'), ('x86_64', 'i386'), '3.7.1 (default, Dec 14 2018, 13:28:58) \n[Clang 4.0.1 (tags/RELEASE_401/final)]')**
[OpenMDAO_install.txt](https://github.com/OpenMDAO/OpenMDAO/files/2859159/OpenMDAO_install.txt)

**Comment by JustinSGray** [comment] 2019-02-13 15:13
duplicate of #841. This issue will be fixed in v2.6.0. Your installation is fine, these tests were broken (they are fixed as of #20b3053 on master

**Closed** 2019-02-19 14:29 UTC
